Controllers/GamesController.cs
using Microsoft.AspNetCore.Mvc;
using infiniteworlds_frontend.Models;
using infiniteworlds_frontend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.JsonPatch;
using System.Security.Claims;
using infiniteworlds_fronted.Models;
using Microsoft.AspNetCore.Hosting.Server.Features;
using Microsoft.AspNetCore.Authorization;

namespace infiniteworlds_frontend.Controllers
{
    public class GamesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GamesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Games
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var games = await _context.Games.ToListAsync();
            return View(games);
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var game = await _context.Games
                .FirstOrDefaultAsync(g => g.GameId == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // GET: Games/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }





        // POST: Games/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Game game)
        {
            Console.WriteLine($"el precioo es {game.Price}");
            if (ModelState.IsValid)
            {
                // Validar si la URL de la imagen es proporcionada
                if (string.IsNullOrEmpty(game.ImageFilePath))
                {
                    ModelState.AddModelError("ImageFilePath", "The image URL is required.");
                }

                // Intentar agregar el juego a la base de datos si el modelo es válido
                if (ModelState.IsValid)
                {
                    try
                    {
                        
                        _context.Add(game);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", "Error saving the game to the database.");
                        Console.WriteLine($"Database saving error: {ex.Message}");
                    }
                }
            }
            else
            {
                // Registrar el estado del modelo si no es válido
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }

            return View(game);
        }



        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var game = await _context.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        // POST: Games/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("GameId,Name,Descripcion,Genero,ReleaseDate,ImageFilePath")] Game game)
        {
            if (id != game.GameId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameExists(game.GameId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View(game);
        }


        // GET: Games/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var game = await _context.Games
                .FirstOrDefaultAsync(g => g.GameId == id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var game = await _context.Games.FindAsync(id);
            if (game != null)
            {
                _context.Games.Remove(game);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        // Método auxiliar para verificar si el registro Game existe
        private bool GameExists(int id)
        {
            return _context.Games.Any(e => e.GameId == id);
        }

        // Método para manejar PATCH (simulado)
        public async Task<IActionResult> PatchGame(int id, [FromBody] JsonPatchDocument<Game> patchDoc)
        {
            if (patchDoc == null)
            {
                return BadRequest("Patch document is null.");
            }

            var game = await _context.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }

            // Aplicar el parche al objeto Game encontrado
            patchDoc.ApplyTo(game, ModelState);

            // Verificar el estado del modelo después de aplicar el parche
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                await _context.SaveChangesAsync(); // Guardar los cambios en la base de datos
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GameExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent(); // Utiliza NoContent() para indicar que la solicitud fue exitosa pero no devuelve contenido
        }

         [Authorize]
        public async Task<IActionResult> MyGames()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var purchasedGames = await _context.PurchasedGames
                .Include(pg => pg.Game)
                .Where(pg => pg.UserId == userId)
                .Select(pg => pg.Game)
                .ToListAsync();

            return View(purchasedGames); // Asegúrate de que este es un IEnumerable<Game>
        }

        [HttpPost]
        public async Task<IActionResult> Purchase(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Lógica para verificar si el juego ya ha sido comprado y realizar la compra
            var game = await _context.Games.FindAsync(id);

            if (game == null)
            {
                return NotFound();
            }

            // Crear la entrada de juego comprado para el usuario
            var purchasedGame = new PurchasedGame
            {
                UserId = userId,
                GameId = game.GameId,
                PurchaseDate = DateTime.Now
            };

            _context.PurchasedGames.Add(purchasedGame);
            await _context.SaveChangesAsync();

            // Redirigir a la lista de juegos comprados o a alguna otra página
            return RedirectToAction("MyGames");
        }
        [HttpGet]
        public async Task<IActionResult> Cart()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var cartItems = await _context.ShoppingCartItems
                .Include(c => c.Game)
                .Where(c => c.UserId == userId)
                .ToListAsync();

            return View(cartItems);
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(int gameId)
        {
            if (gameId <= 0)
            {
                return BadRequest("El ID del juego es inválido.");
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var game = await _context.Games.FindAsync(gameId);

            if (game == null)
            {
                return NotFound();
            }

            var existingCartItem = await _context.ShoppingCartItems
                .FirstOrDefaultAsync(c => c.UserId == userId && c.GameId == gameId);

            if (existingCartItem != null)
            {
                existingCartItem.Quantity++;
            }
            else
            {
                var cartItem = new ShoppingCartItem
                {
                    UserId = userId,
                    GameId = gameId,
                    Quantity = 1
                };

                _context.ShoppingCartItems.Add(cartItem);
            }

            await _context.SaveChangesAsync();

            TempData["Success"] = "Juego agregado al carrito.";
            return RedirectToAction("Cart");
        }

        // Método para mostrar la página de Checkout
        [HttpGet]
        public async Task<IActionResult> Checkout()
        {
            // Obtener el ID del usuario actual
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Obtener los juegos en el carrito del usuario actual
            var cartItems = await _context.ShoppingCartItems
                .Include(c => c.Game) // Incluir la información del juego asociado
                .Where(c => c.UserId == userId)
                .ToListAsync();

            if (cartItems == null || !cartItems.Any())

Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InfiniteWorlds</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sitepage.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>


    <link rel="stylesheet" href="~/css/infiniteworlds_fronted.styles.css" asp-append-version="true" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">InfinityWorlds</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarS"
                    aria-controls="navbarS" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarS">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a href="#" class="nav-link">Quienes Somos</a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("MyGames", "Games")" class="nav-link">Mis Juegos</a>
                        </li>
                        <li class="nav-item">
                            <a href="#section-soporte" class="nav-link">Soporte</a>
                        </li>
                        
                        <li class="nav-item">
                            <a href="" class="nav-link">Noticias</a>
                        </li>
                        <!-- Dropdown para Cuenta de Usuario o Inicio de Sesión/Registro -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="navbarDropdown"
                                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <!-- Icono de cuenta o inicial del usuario -->
                                <div id="userCircle"
                                    class="rounded-circle bg-primary text-white d-flex justify-content-center align-items-center"
                                    style="width: 30px; height: 30px;">
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        @User.Identity.Name.Substring(0, 1).ToUpper()
                                        <!-- Primera letra del nombre de usuario -->
                                    }
                                    else
                                    {
                                        <i class="bi bi-person-circle" title="Cuenta"></i>
                                        <!-- Icono de usuario si no está autenticado -->
                                    }
                                </div>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end navbar-dark bg-dark"
                                aria-labelledby="navbarDropdown">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <!-- Opciones si el usuario está autenticado -->
                                    <li>
                                        <a class="dropdown-item nav-link" asp-controller="UserProfile"
                                            asp-action="Index">Perfil</a>
                                    </li>

                                    <li>
                                        <a class="dropdown-item nav-link" href="#">Configuración</a>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li>
                                        <!-- Cerrar Sesión -->
                                        <form asp-controller="Account" asp-action="Logout" method="post" class="d-inline">
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="dropdown-item nav-link">Cerrar sesión</button>
                                        </form>
                                    </li>
                                }
                                else
                                {
                                    <!-- Opciones si el usuario NO está autenticado -->
                                    <li>
                                        <a class="dropdown-item nav-link" asp-controller="Account" asp-action="Login">Inicio
                                            de Sesión</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item nav-link" asp-controller="Account"
                                            asp-action="Register">Registrarse</a>
                                    </li>
                                }
                            </ul>
                        </li>

                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - InfiniteWorld. Todos los derechos reservados.<a asp-controller="Home"
                asp-action="Privacy">Privacy</a>
            <a href="#">Política de Privacidad</a> |
            <a href="#">Términos de Servicio</a> |
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>